service: post-lambda

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DB_HOST: ${process.env.DB_HOST}
    DB_PORT: ${process.env.DB_PORT}
    DB_USER: ${process.env.DB_USER}
    DB_PASSWORD: ${process.env.DB_PASSWORD}
    DB_NAME: ${process.env.DB_NAME}
    LOG_ACTIVE: ${process.env.LOG_ACTIVE}
    LOG_LEVEL: ${process.env.LOG_LEVEL}
    API_BASE_URL: ${process.env.API_BASE_URL}

package:
  individually: true

custom:
  serverless-offline:
    port: 3003

functions:
  getMovieTheater:
    handler: app/handler.get
    events:
      - http:
          path: sala-cine/{id}
          method: get
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
